name: overlay_support
description: proivder support for overlay, easy to build toast and internal notification
version: 1.0.5
author: YangBin <yangbinyhbn@gmail.com>
homepage: https://github.com/boyan01/overlay_support

environment:
  sdk: '>=2.12.0-29.10.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  async: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: