name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Setup flutter
      run: |
        git clone https://github.com/flutter/flutter.git -b stable --depth 1
        ./flutter/bin/flutter doctor
    - name: Flutter unit test
      run: ./flutter/bin/flutter test --coverage --coverage-path=lcov.info
    - name: Report code coverage
      run: bash <(curl -s https://codecov.io/bash)
