name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      - name: Setup Flutter
        uses: subosito/flutter-action@v1.1.1
        with:
          channel: 'master'
      - run: flutter config --enable-web
      - run: flutter pub get

      - name: Flutter unit test
        run: flutter test --coverage --coverage-path=lcov.info

      - name: Report CodeCov
        uses: codecov/codecov-action@v1.0.2
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: lcov.info
          flags: unittests

      - name: Deploy web To GH-Page
        uses: JamesIves/github-pages-deploy-action@master
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BASE_BRANCH: master
          BRANCH: gh-pages
          FOLDER: example/build/web/
          BUILD_SCRIPT: cd example && flutter build web
